### ISSUE TITLE
Simple validation report error with Infix Expression

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#206]
The simple validation report an error if the simple expression is constructed with Infix expression even if the expression is still valid

> simple("http://myhost?bridgeEndpoint=true&type=$simple{header."+ ImportConstants.APPLICATION_HEADER +"}&ids=$simple{header." + ImportConstants.USER_ID_HEADER + "}")

Until we get better parsing of Infix Expression we should ignore this

**Comment by davsclaus** [comment]
This is likely the same with the endpoint validator.

**Comment by davsclaus** [comment]
Okay so we will turn this off for those complex structures until we later can come up with a better solution. For example for some simpler strings where you concat using new lines etc we can try to assemble that into a combined url to validate. It does add complexities to find out with text range where the problem is.
